server:
  port: 8088
spring:
  profiles:
    active: zhuxj
  application:
    name: z-dtx-transport-service

logging:
  level:
    ch.qos.logback.core: warn

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*Mapper.xml

swagger2:
  apiInfo:
    title: Title
    version: 1.0
    description: Swagger-UI
    contact:
      name: zhuxj
      url: http://127.0.0.1
      email: 870324066@qq.com
  apis:
    basePackage: org.zipper.transport.controller
