server:
  port: 8088
spring:
  profiles:
    active: dev
  application:
    name: z-dtx-transport-service

logging:
  level:
    ch.qos.logback.core: warn

mybatis:
  configuration:
    map-underscore-to-camel-case: true
